### ISSUE TITLE
Create UserController put and delete methods

### ISSUE THREAD

**Issue by technetos** [cs-club-appdev/cs-club-calendar-server#22]
The routes you are writing are PUT /users/:id and DELETE /users/:id .

The skeleton for these functions has already been created in the User Controller file. Please implement the two functions. You can access the id via req.params.id .

You will need to query the user collection using  [Mongoose.js](http://mongoosejs.com/docs/queries.html), the link takes you to the documentation for querying.

Note: the field for id in Mongodb is '_id' not 'id'.

**Comment by technetos** [comment]
I decided that a great way to get people with less knowledge and skills more knowledge and skills is to pair them on issues with people who do have knowledge and skills.  Please talk with each other and myself, Danny, or Nick if need be.  

Happy Coding!

**Comment by rupsis** [comment]
That's a great idea.

**Comment by trentspi** [comment]
Both put and delete methods have been completed and merged....
